name: Codespell test

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: codespell-project/actions-codespell@v2.1
      with:
        check_filenames: true
        check_hidden: true
          # Add comma separated list of words to ignore (sorted alphabetically, case sensitive)
        ignore_words_list: adin,ADn,aNULL,carryIn,cconfiguration,ciph,cLen,cliKs,creen,ede,Fo,haveA,hashIn,larg,LEAPYEAR,inCreated,inOut,inout,Merget,parm,parms,rIn,ser,siz,Te,te,TOOM,userA,vie,vlaue
