name: wolfCLU

on:
  push:
  workflow_call:

jobs:
  wolfclu:
    name: Create multi-arch image
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'bandi13' }} # Only run for specific repo
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: Docker/wolfCLU
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            NUM_CPU=4
#            DUMMY=${{ github.sha }}
          pull: true
          push: true
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=Simple wolfCLU multi-arch image
          tags: ghcr.io/bandi13/wolfclu:latest,ghcr.io/bandi13/wolfclu:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.request("GET /${{ env.OWNER }}/packages/container/${{ env.PACKAGE_NAME }}/versions",
              { per_page: ${{ env.PER_PAGE }}
            });
            for(version of response.data) {
                if (version.metadata.container.tags.length == 0) {
                    console.log("delete " + version.id)
                    const deleteResponse = await github.request("DELETE /${{ env.OWNER }}/packages/container/${{ env.PACKAGE_NAME }}/versions/" + version.id, { });
                    console.log("status " + deleteResponse.status)
                }
            }
        env:
          OWNER: 'bandi13'
          PACKAGE_NAME: 'wolfclu'
          PER_PAGE: 100
