name: wolfCLU

on:
  push:
  workflow_call:

jobs:
  wolfclu:
    name: Create multi-arch image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: Docker/wolfCLU
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=Simple wolfCLU multi-arch image
          tags: ghcr.io/bandi13/wolfclu:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

